import processInputWithRegex from '@/services/regex'
import { Item } from '@/types'
import { Container, Heading, Input, Stack } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { DefaultContainer } from './components/DefaultContainer'
import { Header } from './components/Header'
import { Message } from './components/Message'
import { MessageContainer } from './components/MessageContainer'
import { MessageInput } from './components/MessageInput'

export default function Home() {

  const [text, setText] = useState("")
  const [isAllMatch, setIsAllMatch] = useState(false)
  const [items, setItems] = useState<Item[]>([])

  useEffect(() => {
    const { name, quantity, unit } = processInputWithRegex(text)
    
    if ((!name || !unit || !quantity || !text)) {
      setIsAllMatch(false)
    } else {
      setIsAllMatch(true)
    }
  }, [text])

  const handleSubmit = () => {
    if(!isAllMatch) return

    setItems([...items, processInputWithRegex(text) as Item])
    
  }

  return (
    <>
      <Head>
        <title>Lista de Compras</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultContainer>
        <Header/>
        <MessageContainer>
          {
            items.map((item, index) => {
              return (
                <Message key={index}>
                  {`${item.quantity}${item.unit} ${item.name}`}                  
                </Message>
              )
            })
          }
        </MessageContainer>
        <MessageInput 
          text={text}
          setText={setText} 
          isAllMatch={isAllMatch}
          handleSubmit={handleSubmit}
        />
      </DefaultContainer>
    </>
  )
}
